### ISSUE TITLE
Passing parameters with spaces

### ISSUE THREAD

**Issue by Frogli** [suransys/omniscli#1]
Passed week I experimented a little bit with this tool. It was great fun. Thank you very much for making this available. I run up a problem mentioned in the subject. I followed the steps below which I got from the readme page:

> Accessing arguments
> 
> Use the inherited $getCLIArgument(piArgument) method to get the arguments from the command line. Please note the command will be argument 1, and the remaining arguments will be numbered starting at 2.
> 
> For example, running this command:
> 
> omniscli say_hello 'first name' 'last name'
> With this $cli_say_hello method:
> 
> Calculate lcName as con($cinst.$getCLIArgument(2)," ",$cinst.$getClIArgument(3)
> Will set the lcName variable to "first name last name".'''

The problem I encountered was that if I run the command
```
omniscli say_hello 'first name' 'last name'
```
I get as output

```
first name
```

Somehow each word is treated as a parameter. I googled around, but could not find a working solution. 

I hope that you have a solution for this.

Oh I forgot to say I use MacOS 10.12.6

**Comment by barkingfoodog** [comment]
Sorry for the delay in getting back to you...I've been swamped lately!

I [added a test](https://github.com/suransys/omniscli/commit/905153116ee95691c517575bcfe95907dc21ff76) to `oOmnisCli.$_parseArguments()` to try and demonstrate this error, but the test correctly sees `'foo bar' 'baz biff'` as two arguments.

There could be some command-line parsing causing the issue. What platform and shell are you using?

**Comment by Frogli** [comment]
No problem, we all have busy schedules... 😉
I use MacOs 10.12.6 and tested it in Bash and zsh. Both give the same results. I noticed it does work if you wrap the arguments with single and double quotes.
eg 
"/Applications/Omnis Studio Runtime 8.0.3.5 x64.app/Contents/MacOS/bin/omniscli" Hello "'foo bar'" "'baz biff'"

**Comment by barkingfoodog** [comment]
I found the problem. The `omniscli` and `omniscli.ps1` scripts were consuming the single quotes. I checked in a fix, so grab a new copy of `omniscli` and see if that fixes the issue.

**Comment by Frogli** [comment]
Hi Alex,

Thanks for the quick fix. Am I correct that only the Windows version of the script needed a fix? I only noticed this error on MacOS. I have not used the Windows version yet. But nice to know it is fixed.

**Comment by barkingfoodog** [comment]
Both scripts needed a fix. The script takes its arguments and stores them in an environment variable for Omnis to read. The quotes kept the arguments grouped properly in the script, but the script didn’t re-add them for Omnis to see. Both scripts now quote each argument to ensure Omnis parses them as the user intended.

**Comment by Frogli** [comment]
Hi Alex,

I think you only committed the Windows fix and not the MacOS fix. Could you also commit the MacOS fix.

**Comment by barkingfoodog** [comment]
Yeah...I squashed the commits for the Mac and Windows scripts and went one revision too far for the release notes. If you check the code for `omniscli` you'll see a `shift` to get the command, then a `for` loop to wrap the arguments in single quotes. This is the fix for this issue. Can you give it a try on your box and verify?

**Comment by Frogli** [comment]
Ah sorry, I was confused by the information GitHub gave me. When I compared the revisions of the omniscli file I saw the change and it also works at my computer!

Thanks!
